# POST http://localhost:4321/building/create HTTP/1.1
# content-type: application/json

# {
#     "block_no" : "blocktest",
#     "building_owner" : "namgay",
#     "cidOwner" : "10503000532",
#     "contactOwner" : "77385314",
#     "constYear" : "2020",
#     "floors" : "1",
#     "attic" : true,
#     "basement" : false,
#     "buildingStyle" : "no style",
#     "structureType" : "no type",
#     "materialType" : "wood",
#     "roofMaterial" : "cgi",
#     "sewerTreatment" : "no",
#     "wasteCollection" : "no",
#     "wasteCollectionFrequency" : "not much",
#     "waterSupply" : "no",
#     "buildingUse" : "residential",
#     "residentialUnits" : 1,
#     "commercialUnits" : 0,
#     "officeUnits" : 0,
#     "user_id":0
# }

# GET http://localhost:4321/building/get/1a

# PATCH http://localhost:4321/building/update HTTP/1.1
# Content-Type: application/json

# {
#     "id":2,
#     "building_owner":"Namgay Dorji"
# }

# DELETE http://localhost:4321/building/delete/1

# Dzongkhag service

# GET http://localhost:4321/dzongkhag/get-all

# POST http://localhost:7777/household/create Http/1.1
# Content-Type: application/json

# {
#     "structure_id":123,
#     "head":"kinley",
#     "gender":"m",
#     "cidHead":"1230000",
#     "age":23,
#     "martialStatus":"single",
#     "employment":"civil",
#     "employmentOrg":"mowhs",
#     "yearsInService":5.2,
#     "numberHousehold":4,
#     "incomeEarner":1,
#     "householdIncome":25000.0,
#     "ownHouse":false,
#     "censusDzo":"HAA",
#     "distToWork":7.4,
#     "commuteCost":45,
#     "houseOccupation":"no",
#     "rent":8500,
#     "typeRent":"stest",
#     "rooms":4,
#     "yearsResiding":4,
#     "rentIncreased":false,
#     "rentWaived":false,
#     "rentWaivedPrecent":50,
#     "ownType":"test",
#     "howOwned":"constructed",
#     "yearAcquisition":1,
#     "cost":1230,
#     "meanFinance":"bank",
#     "emi":42000,
#     "user_id":1,
#     "members":[
#         {"idNumber":123,"age":24,"gender":"Male","type":"CID"},
#         {"idNumber":321,"age":24,"gender":"Male","type":"CID"}
#     ]
# }

# GET http://localhost:4321/household/get-all/123


# PATCH http://localhost:4321/household/update HTTP/1.1
# Content-Type: application/json

# {
#     "id":5,
#     "howOwned":"constructed"
# }

# DELETE http://localhost:4321/household/delete/5

# GET http://localhost:4321/household/get/4


# POST http://localhost:4321/image/create HTTP/1.1
# Content-Type: application/json

# {
#     "structure_id":123,
#     "user_id":0,
#     "uri":"/uploads/123.png"
# }

# GET http://localhost:4321/image/get-all/123

# GET http://localhost:4321/image/get/1

# PATCH http://localhost:4321/image/update HTTP/1.1
# Content-Type: application/json

# {
#     "id":1,
#     "structure_id":111
# }

# DELETE http://localhost:4321/image/delete/1

# TODO test structure routes

# POST http://localhost:7777/member/create-bulk HTTP/1.1
# Content-Type: application/json

# {
#     "members":[
#         {"hhId":1,"idNumber":10503000532,"age":26,"gender":"male","type":"CID"},
#         {"hhId":1,"idNumber":10503000527,"age":54,"gender":"female","type":"CID"}
#     ]
# }

# DELETE http://localhost:7777/building/delete/1 

# DELETE http://localhost:7777/household/delete/1 
# DELETE http://localhost:7777/structure/delete/1481


PATCH http://localhost:7777/household/update HTTP/1.1
Content-Type: application/json

{
    "id":3,
    "members":[
        {"id":4,"hhId":65,"idNumber":10503000532,"age":26,"gender":"male","type":"CID"},
        {"id":5,"hhId":65,"idNumber":10503000527,"age":54,"gender":"female","type":"CID"}
    ]
}